//
// Written by Andrew Chapman - April 2003
//
// example usage:  constrainCurvePointToLocator("curve1", 4, "locator1");
//

global proc constrainCurvePointToLocator(string $curveName, int $pointIndex, string $locatorName)
{
  expression -s ("float $pos[] = `getAttr " + $locatorName + ".worldPosition`; xform -ws -translation $pos[0] $pos[1] $pos[2] " + $curveName + ".cv[" + $pointIndex + "]"); 
}
