#!/bin/sh

#
# Rush - Rush boot script for MAC/OSX, resides in /Library/StartupItems/Rush/Rush 
# 12/14/01 erco@3dsite.com -- Original implementation
# 05/05/05 erco@3dsite.com -- Mods for Tiger / 10.4
# 03/19/08 erco@3dsite.com -- Mods for Leopard / 10.5
#
#        Rush is a render queue daemon that manages network rendering
#

# From launchd(8):
#     "At some point in the future, we hope to completely phase out 
#      the use of rc." OK.. anticipate /etc/rc.common may disappear..
#
if [ -r /etc/rc.common ]; then . /etc/rc.common; fi

export RUSHDIR=/usr/local/rush
export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec:${RUSHDIR}/bin"
RUSHSERVER=${RUSHSERVER:--YES-}		# assume -YES- if unset
ARG1=${1:-start}			# assume 'start' if unset

# LOG A MESSAGE TO CONSOLE/SYSTEM LOG
function Log()
{
    # In OSX 10.5, Apple removed 'ConsoleMessage' %^/
    if [ -x /usr/libexec/ConsoleMessage ]; then ConsoleMessage "$*"; fi
    logger -s -t Rush "$*"
}
    
# Log "$0 invoked with '$*', RUSHSERVER='$RUSHSERVER'"

if [ "${RUSHSERVER}" = "-NO-" ]; then 
    Log "rush not starting: disabled in /etc/hostconfig"
    exit
fi

# HANDLE STOP/START
#    Calling this script with no args implies 'start'.
#
case "$ARG1" in
    stop)
	Log "Stopping Rush Render Queue"
	${RUSHDIR}/etc/S99rush stop
        ;;

    start)
	Log "Starting Rush Render Queue"
	${RUSHDIR}/etc/S99rush start
        ;;

    restart)
	# RESTART THE DAEMON
	Log "Restarting Rush Render Queue"
	${RUSHDIR}/etc/S99rush restart
	;;

    *)
	echo "usage: $0 {start|stop|restart}"
	;;
esac

exit 0
