#!/bin/bash


### Description ###


echo ‘START ${0}’
HERE=$(dirname $0)
echo $HERE > ~/.startDirectory
# variable is assigned the directory this script is located in 
echo ‘HERE ${HERE}’

open $HERE/bin/UTS.terminal
