#!/bin/sh

### script from Greg Ercolano  seriss.com/rush
###
### edited by Pascal Grosvenor for DAB setup  
### edited by  matt gidney
### adding Labshare into mounts
### last modified  16/7/2014
###
### Mount File Servers -- Set up local mounts for our file server
###
###      Save this file as /Library/StartupItems/MountFileServers/MountFileServers
###      and make sure the files/dirs are owned by root/wheel and modes are 755
###      (rwx-r-xr-x).
###	

##########################################################
# SUBROUTINE: MOUNT A REMOTE DRIVE
#
#    NOTE: Use ip addresses in the remote device name, do NOT use hostnames.
#          This avoids assuming DNS fully operational during boot.
#          Often DNS is unstable during boot, even with boot dependencies.
#
MountNFS()
{
    #remdrive="138.25.145.200:/Volumes/Renderfarm"   # $1 -- the remote drive,  eg. "192.168.1.10:/jobs"
    remdrive=$1
    #localdir="/Volumes/Renderfarm"	 	    # $2 -- local mount point, eg. "/net/jobs"
    localdir=$2
    #nfsflags="intr,bg,tcp,vers=3"		    # $3 -- nfs flags, eg. "rw,intr,bg,vers=3"
    nfsflags=$3

    # ENSURE MOUNT POINT EXISTS
    if [ ! -d "$localdir" ]; then
	$LOGGER "Creating mount point $localdir"
	mkdir -p -m 755 "$localdir"
    fi

    # ALREADY MOUNTED? DONT MOUNT TWICE
    if mount | grep -q "$localdir"; then
	$LOGGER "$localdir already mounted"
    else
	$LOGGER "Mounting '$remdrive' on '$localdir'"
	( mount -t nfs -o "$nfsflags" "$remdrive" "$localdir" ) 2>&1 | $LOGGER
    fi
}

MountSMBFS()
{
    #remdrive="138.25.145.195:/Volumes/Labshare"   # $1 -- the remote drive,  eg. "192.168.1.10:/jobs"
    remdrive=$1
    #localdir="/Volumes/Labshare"	 	    # $2 -- local mount point, eg. "/net/jobs"
    localdir=$2
    #nfsflags="nonotification"		    # $3 -- nfs flags, eg. "rw,intr,bg,vers=3"
    smbfsflags=$3


    # ENSURE MOUNT POINT EXISTS
    if [ ! -d "$localdir" ]; then
	$LOGGER "Creating mount point $localdir"
	mkdir -p -m 755 "$localdir"
    fi

    # ALREADY MOUNTED? DONT MOUNT TWICE
    if mount | grep -q "$localdir"; then
	$LOGGER "$localdir already mounted"
    else
	$LOGGER "Mounting '$remdrive' on '$localdir'"
	( mount -t smbfs -o "$smbfsflags" "$remdrive" "$localdir" ) 2>&1 | $LOGGER
    fi
}
##########################################################
# SUBROUTINE: UNMOUNT THE SPECIFIED DRIVE
Umount()
{
    #localdir="/Volumes/Renderfarm"		# $1 -- local mount point, eg. "/net/jobs"
    localdir=$1	
    $LOGGER "Un-mounting '$localdir'"
    umount "$localdir" 2>&1 | $LOGGER
}


##########################################################
### MAIN
###
if [ -x /etc/rc.common ]; then . /etc/rc.common; fi
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/libexec

if [ "`tty`" = "not a tty" ]; then LOGGER="logger    -t MountFileServers"
else                               LOGGER="logger -s -t MountFileServers"; fi

# Handle stop/start/restart
ARG1=${1:-start}                 # assume 'start' if unset
case "$ARG1" in

    start)
        ### MOUNT ALL SERVERS ON BOOT
	MountNFS "138.25.145.200:/Volumes/Renderfarm"    "/Volumes/Renderfarm"      "intr,bg,tcp,vers=3"        # OSX/TCP
	##### dont mount this way because of authentication
	#MountSMBFS "//138.25.145.195/Labshare"   "/Volumes/Labshare"      "noowners"        # OSX/TCP
        ;;

    stop)
        ### UN-MOUNT ALL SERVERS ON SHUTDOWN
	Umount /Volumes/Renderfarm
	#Umount /Volumes/Labshare
	;;

    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
